### ISSUE TITLE
Documentation - Please add url Parameter to [solr]

### ISSUE THREAD

**Issue by 1letter** [4teamwork/ftw.solr#117]
please add the following to the docs, otherwise you get an installation error when the buildout runs
```
[solr]
recipe = ftw.recipe.solr
cores = mycore
url = http://archive.apache.org/dist/lucene/solr/7.2.1/solr-7.2.1.tgz
```

**Comment by buchi** [comment]
ftw.recipe.solr 1.2.0 now uses the archive url by default.
