### ISSUE TITLE
Improve error logging for failing documents.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/ftw.solr#160]
Currenlty solr error logging for failing documents (during `sync` and `reindex` at least) is very minimal. It just outputs
```
2020-03-27 12:11:36 ERROR ftw.solr.connection Update command failed. Server responded with code 400, Invalid Date in Date Math String:'2015-04-07T14:43:60.000Z'.
```
This is very hard to debug as there is no reference to the failing document. We should at least try to include id of a failing document, so we can find and debug it easier.

Not sure if it is possible to do so with batch commits, but should we decide to implement a fallback strategy as described in https://github.com/4teamwork/ftw.solr/issues/159 we should also improve logging to improve debuggability.

**Comment by njohner** [comment]
Moved to Jira: https://4teamwork.atlassian.net/browse/GEVER-183
