### ISSUE TITLE
Should install collective.solr as well

### ISSUE THREAD

**Issue by jean** [4teamwork/ftw.solr#40]
Installation of `ftw.solr` at *Add-ons* should install `collective.solr` as well.

**Comment by mbaechtold** [comment]
This should be the case now: https://github.com/4teamwork/ftw.solr/blob/master/ftw/solr/profiles/default/metadata.xml#L4

@jone, can you confirm this?

**Comment by jone** [comment]
Yes, installing `ftw.solr` has always installed `collective.solr`.

**Comment by jone** [comment]
https://github.com/4teamwork/ftw.solr/commit/da12aeb1d15600b1505fb2c95000e3d40344bdd8#diff-76302de8682725e0e3ed02b31c8f6ea5R5
