### ISSUE TITLE
`link-https` links not working

### ISSUE THREAD

**Issue by bierik** [4teamwork/ftw.solr#59]
On `https` Systems Plone wraps almost every link with `link-https`. This breaks the styling and dropdown functionality. Adding the `link-plain` class should prevent this behavior.

**Comment by jone** [comment]
@bierik what's the state of this one? What are the difficulties?

**Comment by bierik** [comment]
This error occurred at https://demo-bl.4teamwork.ch/. When #66 has been merged the `mark_special_link.js` should be reactivated in the javascript registry.
